### PR TITLE
Removed management of /etc/mesos/zk

### PR DESCRIPTION
**Pull request by potto007**
Using this module without module-based hiera is problematic for the /etc/mesos/zk file now, as it is removed if it exists. Because this module adds ZK="<zk URL(s)" to /etc/default/mesos-master and MASTER="<zk URL(s)" to /etc/default/mesos-slave - which is what Mesos ends up using. /etc/mesos/zk, on the other hand, is hardcoded in the Marathon framework to be used. I have created a module to configure Marathon, and I am having it manage /etc/mesos/zk.

Would you be agreeable to removing management of /etc/mesos/zk as done in my PR?

Thanks,
Paul

### CODE REVIEW

**Comment by potto007** [comment]
I spent a fair amount of time trying to understand why Travis-CI tests were failing for me while they had passed for you a month ago. Performing a diff of the Travis build logs, I discovered that Puppet 4.0 was installing for me, while Puppet 3.7.5 had been installing for you. This led me to find that the PUPPET_VERSION listed in travis.yml was not being honored, because it was not used in the Gemfile. I have fixed that.

**Comment by deric** [comment]
Yeah, the travis.yml definitely needs some updates.

I'm afraid I can't accept the PR as it is. It would be breaking change, at least for some users.  I agree it is redundant to define ZooKeeper in `/etc/default/mesos-master`, `/etc/default/mesos-slave` and `/etc/mesos/zk`. We ended up doing it so, as sort of rapid code evolution.

Mesosphere deb package defines ZK variable in [`/etc/default/mesos-master`](https://github.com/mesosphere/mesos-deb-packaging/blob/master/default/mesos-master) as:
```
ZK=`cat /etc/mesos/zk`
```
It would make more sense to define ZooKeeper url just in one place, instead of 3 places as it is now. 

Instead of complete removal of `/etc/mesos/zk` management, could you added parameter `manage_zk_file` or something like this, so that this feature could be disabled?

**Comment by potto007** [comment]
Totally understandable about not implicitly removing management of `/etc/mesos/zk`. I'll go ahead with creating a variable to disable `/etc/mesos/zk` management.

**Comment by potto007** [comment]
Despite the unit tests, this doesn't actually work with the current organization of the module. When mesos::slave is called, it can be passed `manage_zk_file`, but that variable is not passed to mesos::config. 

I am actually going to approach this another way. Even with a conditional block around the file resource, Puppet still sees it as a duplicate definition when I also have my Marathon module trying to manage the resource.

I am going to close my PR and make a new one with just the Travis-related fixes.

- Paul

**Comment by deric** [comment]
> mesos::slave is called, it can be passed manage_zk_file, but that variable is not passed to mesos::config

That's correct. In order to avoid configuration repetitions `mesos::config` is shared between slave and master. Thus,
```puppet
class{'mesos':
  manage_zk_file => false
}
class {'mesos-slave':
#...
}
```
should install `mesos-slave` without `/etc/mesos/zk`.

Or with Hiera you just define property (shared for all masters and slaves): 
```yaml
mesos::manage_zk_file: false
```
and simply include slave to your node:
```puppet
class {'mesos-slave':
#...
}
```
Now it should "magically" not manage `/etc/mesos/zk`.

> I am going to close my PR and make a new one with just the Travis-related fixes.

You could have just rebased the PR.

**Comment by potto007** [comment]
Good points! I was so focused on figuring out an elegant way on the a Marathon end that I overlooked that. 

I'll create a new PR and reference this one for continuity.

**Pull request closed without merging**
